# ini list data dummy buat nampung berbagai macam risiko perusahaan ya
database_risiko = [
    {"id": 1, "nama_risiko": "kegagalan server", "deskripsi": "server down lebih dari 1 jam", "status": "belum dinilai", "skor": 0},
    {"id": 2, "nama_risiko": "serangan ransomware", "deskripsi": "data perusahaan terkunci", "status": "Kritis", "skor": 25},
    {"id": 3, "nama_risiko": "kebocoran data pelanggan", "deskripsi": "database pelanggan diretas dan bocor ke forum gelap", "status": "Sedang", "skor": 5},
    {"id": 4, "nama_risiko": "ddos attack", "deskripsi": "website utama diserang ddos menyebabkan downtime", "status": "Tinggi", "skor": 11},
    {"id": 5, "nama_risiko": "kabel fiber optik putus", "deskripsi": "koneksi internet utama kantor putus akibat galian", "status": "belum dinilai", "skor": 0},
    {"id": 6, "nama_risiko": "vendor bangkrut", "deskripsi": "vendor logistik utama menyatakan pailit secara tiba-tiba", "status": "Tinggi", "skor": 14},
    {"id": 7, "nama_risiko": "phishing email", "deskripsi": "karyawan mengklik tautan phishing dan membahayakan kredensial", "status": "belum dinilai", "skor": 0},
    {"id": 8, "nama_risiko": "perubahan regulasi pajak", "deskripsi": "kenaikan tarif pajak mendadak yang memukul margin", "status": "Rendah", "skor": 1},
    {"id": 9, "nama_risiko": "pemadaman listrik massal", "deskripsi": "mati lampu berhari-hari karena gangguan gardu induk", "status": "belum dinilai", "skor": 0},
    {"id": 10, "nama_risiko": "karyawan kunci resign", "deskripsi": "lead developer aplikasi inti mendadak pindah ke kompetitor", "status": "belum dinilai", "skor": 0},
    {"id": 11, "nama_risiko": "banjir di gudang", "deskripsi": "gudang penyimpanan produk terendam banjir bandang", "status": "Sedang", "skor": 9},
    {"id": 12, "nama_risiko": "kegagalan backup data", "deskripsi": "proses backup mingguan corrupt dan tidak bisa direstore", "status": "belum dinilai", "skor": 0},
    {"id": 13, "nama_risiko": "keterlambatan pengiriman", "deskripsi": "kapal kargo tertahan di pelabuhan akibat cuaca buruk", "status": "Sedang", "skor": 9},
    {"id": 14, "nama_risiko": "pelanggaran uu pdp", "deskripsi": "perusahaan didenda karena tidak mematuhi uu pelindungan data pribadi", "status": "Rendah", "skor": 4},
    {"id": 15, "nama_risiko": "bug pada update aplikasi", "deskripsi": "rilis terbaru menyebabkan aplikasi crash di banyak perangkat", "status": "Sedang", "skor": 5},
    {"id": 16, "nama_risiko": "penipuan keuangan internal", "deskripsi": "manajer keuangan menggelapkan dana operasional", "status": "Tinggi", "skor": 11},
    {"id": 17, "nama_risiko": "kegagalan sistem crm", "deskripsi": "sistem crm down membuat tim sales tidak bisa jualan", "status": "Sedang", "skor": 7},
    {"id": 18, "nama_risiko": "gugatan hukum pelanggan", "deskripsi": "pelanggan menuntut karena produk cacat", "status": "belum dinilai", "skor": 0},
    {"id": 19, "nama_risiko": "inflasi bahan baku", "deskripsi": "harga bahan baku naik drastis bulan ini", "status": "belum dinilai", "skor": 0},
    {"id": 20, "nama_risiko": "demo karyawan", "deskripsi": "buruh pabrik mogok kerja menuntut kenaikan upah", "status": "Tinggi", "skor": 10},
    {"id": 21, "nama_risiko": "serangan malware", "deskripsi": "komputer divisi hr terinfeksi malware pencuri data", "status": "belum dinilai", "skor": 0},
    {"id": 22, "nama_risiko": "kegagalan api pihak ketiga", "deskripsi": "api gateway payment down membuat transaksi gagal", "status": "belum dinilai", "skor": 0},
    {"id": 23, "nama_risiko": "kebakaran ruang arsip", "deskripsi": "korsleting listrik memicu kebakaran di ruang dokumen penting", "status": "Tinggi", "skor": 14},
    {"id": 24, "nama_risiko": "pencurian perangkat kerja", "deskripsi": "laptop direksi dicuri saat perjalanan dinas", "status": "belum dinilai", "skor": 0},
    {"id": 25, "nama_risiko": "sanksi bpom", "deskripsi": "izin edar produk dicabut karena tidak penuhi standar", "status": "belum dinilai", "skor": 0},
    {"id": 26, "nama_risiko": "fluktuasi nilai tukar", "deskripsi": "rupiah melemah drastis membuat beban utang valas naik", "status": "Rendah", "skor": 1},
    {"id": 27, "nama_risiko": "kegagalan mesin pabrik", "deskripsi": "mesin produksi utama rusak butuh waktu lama diperbaiki", "status": "Kritis", "skor": 21},
    {"id": 28, "nama_risiko": "kerusakan armada", "deskripsi": "truk pengiriman mengalami kecelakaan beruntun", "status": "belum dinilai", "skor": 0},
    {"id": 29, "nama_risiko": "sabotase oleh kompetitor", "deskripsi": "pihak tak bertanggung jawab merusak citra di media sosial", "status": "belum dinilai", "skor": 0},
    {"id": 30, "nama_risiko": "pelanggaran kontrak vendor", "deskripsi": "vendor it tidak memenuhi sla uptime 99.9%", "status": "Sedang", "skor": 7},
    {"id": 31, "nama_risiko": "kegagalan audit iso", "deskripsi": "perusahaan gagal mempertahankan sertifikasi iso 27001", "status": "Sedang", "skor": 5},
    {"id": 32, "nama_risiko": "kampanye hitam", "deskripsi": "berita hoaks menyebar luas menjatuhkan reputasi brand", "status": "belum dinilai", "skor": 0},
    {"id": 33, "nama_risiko": "bencana gempa bumi", "deskripsi": "pusat gempa merusak infrastruktur kantor cabang", "status": "belum dinilai", "skor": 0},
    {"id": 34, "nama_risiko": "lonjakan trafik mendadak", "deskripsi": "server tidak kuat menampung trafik promo flash sale", "status": "belum dinilai", "skor": 0},
    {"id": 35, "nama_risiko": "kesalahan transfer dana", "deskripsi": "staf salah input nomor rekening ke pihak luar", "status": "belum dinilai", "skor": 0},
    {"id": 36, "nama_risiko": "pembajakan akun medsos", "deskripsi": "akun twitter resmi perusahaan diambil alih peretas", "status": "belum dinilai", "skor": 0},
    {"id": 37, "nama_risiko": "hilangnya dokumen legal", "deskripsi": "sertifikat tanah perusahaan hilang saat pindahan", "status": "belum dinilai", "skor": 0},
    {"id": 38, "nama_risiko": "keracunan makanan di kantin", "deskripsi": "banyak karyawan dirawat karena makan siang kantor", "status": "belum dinilai", "skor": 0},
    {"id": 39, "nama_risiko": "wabah penyakit menular", "deskripsi": "banyak staf cuti sakit karena pandemi lokal", "status": "Sedang", "skor": 7},
    {"id": 40, "nama_risiko": "kegagalan sistem hrd", "deskripsi": "payroll error mengakibatkan gaji terlambat cair", "status": "belum dinilai", "skor": 0},
    {"id": 41, "nama_risiko": "tuntutan serikat pekerja", "deskripsi": "serikat pekerja membawa kasus ke pengadilan industrial", "status": "Rendah", "skor": 3},
    {"id": 42, "nama_risiko": "klaim asuransi ditolak", "deskripsi": "asuransi aset tidak mencakup kerugian spesifik yang terjadi", "status": "Tinggi", "skor": 10},
    {"id": 43, "nama_risiko": "pencurian kekayaan intelektual", "deskripsi": "desain produk baru dicuri dan dipatenkan pihak lain", "status": "Sedang", "skor": 6},
    {"id": 44, "nama_risiko": "kehilangan akses cloud", "deskripsi": "lupa perpanjang langganan aws menyebabkan instans ditangguhkan", "status": "Sedang", "skor": 6},
    {"id": 45, "nama_risiko": "kerusakan ac server", "deskripsi": "suhu ruang server naik drastis memicu overheat", "status": "belum dinilai", "skor": 0},
    {"id": 46, "nama_risiko": "ketidaksesuaian laporan keuangan", "deskripsi": "auditor eksternal menemukan selisih dana miliaran", "status": "Rendah", "skor": 2},
    {"id": 47, "nama_risiko": "kegagalan strategi marketing", "deskripsi": "campaign bernilai tinggi tidak menghasilkan konversi", "status": "Sedang", "skor": 5},
    {"id": 48, "nama_risiko": "penurunan tren pasar", "deskripsi": "permintaan produk turun akibat pergeseran minat konsumen", "status": "belum dinilai", "skor": 0},
    {"id": 49, "nama_risiko": "persaingan harga tidak sehat", "deskripsi": "kompetitor banting harga secara tidak rasional", "status": "belum dinilai", "skor": 0},
    {"id": 50, "nama_risiko": "pajak impor naik", "deskripsi": "peraturan baru membuat biaya bahan baku impor meroket", "status": "Rendah", "skor": 3},
    {"id": 51, "nama_risiko": "masalah bea cukai", "deskripsi": "barang tertahan di bea cukai berminggu-minggu", "status": "belum dinilai", "skor": 0},
    {"id": 52, "nama_risiko": "kelangkaan cip semikonduktor", "deskripsi": "produksi perangkat elektronik tertunda karena krisis cip", "status": "Kritis", "skor": 24},
    {"id": 53, "nama_risiko": "kecelakaan kerja", "deskripsi": "karyawan terluka parah di area operasional alat berat", "status": "Tinggi", "skor": 12},
    {"id": 54, "nama_risiko": "limbah mencemari lingkungan", "deskripsi": "bocornya pipa limbah memicu protes warga sekitar", "status": "belum dinilai", "skor": 0},
    {"id": 55, "nama_risiko": "keterlambatan vendor it", "deskripsi": "proyek migrasi server tertunda hingga kuartal berikutnya", "status": "Rendah", "skor": 4},
    {"id": 56, "nama_risiko": "kualitas produk menurun", "deskripsi": "ditemukan batch produksi yang tidak lulus qc", "status": "belum dinilai", "skor": 0},
    {"id": 57, "nama_risiko": "kegagalan kampanye pr", "deskripsi": "pernyataan presdir blunder memicu reaksi negatif publik", "status": "belum dinilai", "skor": 0},
    {"id": 58, "nama_risiko": "pencurian stok barang", "deskripsi": "barang di gudang hilang dicuri oleh sindikat internal", "status": "Tinggi", "skor": 14},
    {"id": 59, "nama_risiko": "infrastruktur jalan rusak", "deskripsi": "akses jalan raya ke pabrik terputus akibat longsor", "status": "belum dinilai", "skor": 0},
    {"id": 60, "nama_risiko": "sistem erp down", "deskripsi": "seluruh modul operasional lumpuh total selama 3 hari", "status": "Sedang", "skor": 9},
    {"id": 61, "nama_risiko": "lisensi software kedaluwarsa", "deskripsi": "tidak bisa akses software desain utama karena lisensi mati", "status": "Rendah", "skor": 2},
    {"id": 62, "nama_risiko": "sistem presensi error", "deskripsi": "data kehadiran karyawan bulan ini hilang sebagian", "status": "Kritis", "skor": 17},
    {"id": 63, "nama_risiko": "gangguan satelit", "deskripsi": "komunikasi vsat di daerah terpencil terputus", "status": "Sedang", "skor": 5},
    {"id": 64, "nama_risiko": "komisaris terlibat skandal", "deskripsi": "kasus pribadi elit perusahaan memengaruhi nilai saham", "status": "Tinggi", "skor": 10},
    {"id": 65, "nama_risiko": "karyawan fiktif", "deskripsi": "ditemukan data karyawan yang menerima gaji tapi tidak ada orangnya", "status": "belum dinilai", "skor": 0},
    {"id": 66, "nama_risiko": "insiden keamanan fisik", "deskripsi": "orang tak dikenal menerobos masuk ke area terbatas", "status": "belum dinilai", "skor": 0},
    {"id": 67, "nama_risiko": "kegagalan uji penetrasi", "deskripsi": "ditemukan banyak kerentanan kritis pada sistem yang baru rilis", "status": "Sedang", "skor": 9},
    {"id": 68, "nama_risiko": "kehilangan sertifikat ssl", "deskripsi": "website terbaca tidak aman oleh browser pengguna", "status": "belum dinilai", "skor": 0},
    {"id": 69, "nama_risiko": "bocornya rahasia dagang", "deskripsi": "mantan manajer membocorkan resep rahasia ke publik", "status": "Rendah", "skor": 4},
    {"id": 70, "nama_risiko": "kartel pemasok", "deskripsi": "pemasok utama bersekongkol menaikkan harga material", "status": "Sedang", "skor": 9},
    {"id": 71, "nama_risiko": "kerusakan cctv", "deskripsi": "titik buta tidak terekam saat insiden kehilangan barang", "status": "Tinggi", "skor": 10},
    {"id": 72, "nama_risiko": "kesalahan cetak kemasan", "deskripsi": "kemasan produk salah cantumkan komposisi memicu recall", "status": "Sedang", "skor": 5},
    {"id": 73, "nama_risiko": "pemalsuan tanda tangan", "deskripsi": "dokumen pencairan dana disetujui dengan tanda tangan palsu", "status": "Sedang", "skor": 9},
    {"id": 74, "nama_risiko": "penarikan produk dari pasar", "deskripsi": "produk terbukti mengandung zat berbahaya oleh lab", "status": "Tinggi", "skor": 12},
    {"id": 75, "nama_risiko": "konflik antar departemen", "deskripsi": "deadlock keputusan karena perselisihan divisi sales dan produksi", "status": "belum dinilai", "skor": 0},
    {"id": 76, "nama_risiko": "serangan sql injection", "deskripsi": "database dibobol lewat celah form login website", "status": "Rendah", "skor": 4},
    {"id": 77, "nama_risiko": "gangguan layanan internet", "deskripsi": "isp utama mengalami gangguan backbone internasional", "status": "belum dinilai", "skor": 0},
    {"id": 78, "nama_risiko": "sistem email down", "deskripsi": "karyawan tidak bisa kirim penawaran ke klien", "status": "Tinggi", "skor": 12},
    {"id": 79, "nama_risiko": "kesalahan alokasi budget", "deskripsi": "dana divisi it habis sebelum pertengahan tahun", "status": "Kritis", "skor": 17},
    {"id": 80, "nama_risiko": "investasi proyek bodong", "deskripsi": "perusahaan tertipu pendanaan proyek infrastruktur fiktif", "status": "Sedang", "skor": 5},
    {"id": 81, "nama_risiko": "kehilangan pelanggan vip", "deskripsi": "klien penyumbang omset terbesar memutus kontrak sepihak", "status": "Tinggi", "skor": 12},
    {"id": 82, "nama_risiko": "gagal bayar utang", "deskripsi": "perusahaan terlambat membayar cicilan pinjaman bank", "status": "Tinggi", "skor": 14},
    {"id": 83, "nama_risiko": "insiden tersetrum", "deskripsi": "karyawan tersengat listrik tegangan tinggi saat maintenance", "status": "Sedang", "skor": 6},
    {"id": 84, "nama_risiko": "kegagalan update firewall", "deskripsi": "firewall salah konfigurasi dan memblokir trafik sah", "status": "Rendah", "skor": 2},
    {"id": 85, "nama_risiko": "gangguan cuaca buruk", "deskripsi": "pengiriman via pesawat dibatalkan karena badai", "status": "Sedang", "skor": 9},
    {"id": 86, "nama_risiko": "overcapacity gudang", "deskripsi": "gudang tidak muat menampung lonjakan stok akhir tahun", "status": "Kritis", "skor": 24},
    {"id": 87, "nama_risiko": "hilangnya paket kiriman", "deskripsi": "kurir menghilangkan dokumen kontrak asli di jalan", "status": "Rendah", "skor": 1},
    {"id": 88, "nama_risiko": "kekurangan bahan bakar", "deskripsi": "pasokan solar untuk genset terlambat tiba", "status": "belum dinilai", "skor": 0},
    {"id": 89, "nama_risiko": "kesalahan input data", "deskripsi": "admin salah ketik nominal di faktur tagihan", "status": "Rendah", "skor": 3},
    {"id": 90, "nama_risiko": "gangguan jaringan lokal", "deskripsi": "switch inti rusak menyebabkan lan kantor mati total", "status": "belum dinilai", "skor": 0},
    {"id": 91, "nama_risiko": "penolakan izin usaha", "deskripsi": "pemda menolak perpanjangan izin operasional pabrik", "status": "belum dinilai", "skor": 0},
    {"id": 92, "nama_risiko": "protes masyarakat adat", "deskripsi": "ekspansi lahan ditolak oleh penduduk lokal setempat", "status": "Sedang", "skor": 5},
    {"id": 93, "nama_risiko": "kehabisan stok barang", "deskripsi": "bahan baku habis sebelum pesanan pelanggan selesai diproduksi", "status": "belum dinilai", "skor": 0},
    {"id": 94, "nama_risiko": "kesalahan desain sistem", "deskripsi": "arsitektur tidak skalabel menahan beban masa depan", "status": "Rendah", "skor": 1},
    {"id": 95, "nama_risiko": "ketidakcocokan budaya kerja", "deskripsi": "merger perusahaan menyebabkan gesekan antar staf", "status": "Kritis", "skor": 23},
    {"id": 96, "nama_risiko": "pengunduran diri massal", "deskripsi": "satu divisi pindah serentak karena tidak puas dengan manajemen", "status": "Tinggi", "skor": 11},
    {"id": 97, "nama_risiko": "kegagalan sistem antrean", "deskripsi": "sistem tiket pelanggan error memicu kerumunan panjang", "status": "Sedang", "skor": 9},
    {"id": 98, "nama_risiko": "pelanggaran hak cipta", "deskripsi": "perusahaan menggunakan aset gambar berlisensi tanpa izin", "status": "belum dinilai", "skor": 0},
    {"id": 99, "nama_risiko": "sistem absensi dimanipulasi", "deskripsi": "karyawan titip absen menggunakan celah sistem", "status": "Sedang", "skor": 9},
    {"id": 100, "nama_risiko": "kelalaian prosedur k3", "deskripsi": "pekerja tidak memakai apd berujung cedera", "status": "Rendah", "skor": 2}
]
